league_api_champions:
    path: /static-data/{region}/v1.2/champion
    defaults: { region: euw }

league_api_champion:
    path: /static-data/{region}/v1.2/champion/{id}
    defaults: { region: euw }

league_api_realm:
    path: /static-data/{region}/v1.2/realm
    defaults: { region: euw }