dragnic_league:
    resource: "@DragnicLeagueBundle/Resources/config/league_api_routes.yml"
    prefix: /api/lol

dragnic_league_champion_list:
    path:     /
    defaults: { _controller: dragnic_league.controller.champion:listAction }

dragnic_league_champion_show:
    path:     /champion/{id}
    defaults: { _controller: dragnic_league.controller.champion:showAction }
